### ISSUE TITLE
how to create a rectangle without clean content inside？

### ISSUE THREAD

**Issue by jackywu** [gyim/vim-boxdraw#2]
how to create a rectangle without clean content inside？

**Comment by uzimonkey** [comment]
I was also wondering this. This plugin seemed really useful at first, but it makes it very hard to draw anything. I can't write the label first, because the box drawing overwrites it. I can't use the "draw box with label" command because I don't know how large to draw the box until I write the label. Seems like that's a rather fundamental thing to be missing.

**Comment by gyim** [comment]
My main use case is to draw small architectural diagrams with this plugin and then convert them into png with Ditaa. I draw some large boxes (modules) with short labels in it, and then connect them with arrows. So I haven't needed this functionality yet.

But I agree that this would be a useful feature. Feel free to create a PR. The drawing logic is in Python, and it is quite easy to extend it with a new command.

**Comment by Shane-XB-Qian** [comment]
looks it can workaround by `+-` then `+|`
thanks @gyim create a wonderful plugin !
